version: "3.9"
services:

  back_end:
    build: .
    container_name: back_end
    
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"

    environment:
      - SECRET_KEY=test
      - DEBUG=True
   
 
